MTBorg/d7024e-kademlia

- cmd/kademlia/kademlia.go
- cmd/kademliactl/kademliactl.go
- internal/cmdlistener/cmdlistener.go
This allows for sending commands to the kademlia node
> Implement ipc

- cmd/kademlia/kademlia.go
- cmd/kademliactl/kademliactl.go
- internal/command/command.go
- internal/command/listener/listener.go
- internal/command/parser/parser.go
- internal/commands/ping/ping.go
> Implement command parsing

- cmd/kademlia/kademlia.go
- docker-compose.yml
- go.mod
- internal/command/parser/parser.go
- internal/commands/message/message.go
- internal/message/listener.go
add udp server to kademlia nodes to listen for udp packets on port 1776 including msg command to kademliactl
closes #4
> Add support for sending messages between containers/nodes

- internal/command/parser/parser.go
- internal/commands/exit/exit.go
> Implement CLI exit command

- cmd/kademlia/kademlia.go
- internal/commands/message/message.go
- internal/kademliaid/kademliaid.go
- internal/message/listener/listener.go
- internal/message/message.go
- internal/message/message_test.go
- internal/udpsender/udpsender.go
> Attach node id to sent messages

- internal/command/parser/parser.go
- internal/commands/put/put.go
- internal/network/network.go
- internal/node/node.go
Closes #39, closes #11, closes #9, closes #40 
Adds a put command to kademliactl and the STORE RPC.
I haven't written any tests as that won't really be possible until the network code has been refactored.
> Implement put cli command

- internal/command/parser/parser.go
- internal/commands/getcontacts/getcontacts.go
- internal/commands/getcontacts/getcontacts_test.go
- internal/routingtable/routingtable.go
- internal/routingtable/routingtable_test.go
Added tests to both cli and routingtable. Command now only returns populated contacts and not empty buckets
Closes #47
> 47 view routingtable

- cmd/kademlia/kademlia.go
- cmd/kademliactl/kademliactl.go
- internal/network/network.go
- internal/rpc/parser/parser.go
- internal/rpc/parser/parser_test.go
- internal/rpc/rpc.go
- internal/rpccommand/rpccommand.go
- internal/rpccommands/ping/ping.go
- internal/rpccommands/ping/ping_test.go
- internal/rpccommands/pong/pong.go
- internal/rpccommands/pong/pong_test.go
- internal/rpccommands/store/store.go
- internal/rpccommands/store/store_test.go
- internal/udplistener/udplistener.go
- internal/utils/arrays/array.go
- internal/utils/arrays/arrays_test.go
Refactor some networking code in order to easier test, and adds some tests.
> Refactor code

- scripts/init-cluster.sh
> 57 nodeid self assign

- cmd/kademliactl/kademliactl.go
Fixes issue/bug where the unix socket is not closed properly
> Fix unix socket error

- internal/kademliaid/kademliaid.go
- internal/kademliaid/kademliaid_test.go
Added tests for kademliaid and the random seed is now generated from unix utc nano
> Implement random seed

- docker-compose-dev.yml
- internal/commands/put/put.go
- internal/node/node.go
> Add k and alpha to env

- internal/rpcpool/rpcpool_test.go
> Add tests to rpcpool

- internal/command/listener/listener.go
- internal/commands/get/get.go
- internal/commands/get/get_test.go
- internal/commands/put/put.go
- internal/commands/put/put_test.go
- internal/network/network.go
- internal/node/node.go
- internal/routingtable/routingtable.go
- internal/rpc/parser/parser.go
- internal/rpccommands/findvalue/findvalue.go
- internal/rpccommands/findvalue/findvalue_test.go
- internal/rpccommands/findvalueresp/findvalueresp.go
- internal/shortlist/shortlist.go
Similar issues exists as in #75
> Implement find value rpc

- internal/bucket/bucket.go
- internal/routingtable/routingtable.go
Fixed an issue where FindKClosest could return a list of contacts containing the requestor of the FIND_NODE
> Fix FindKClosest

- docker-compose-dev.yml
- internal/node/node.go
- internal/rpccommands/findnoderesp/findnoderesp.go
- internal/rpccommands/findvalueresp/findvalueresp.go
- internal/rpcpool/rpcpool.go
- scripts/init-cluster.sh
Closes #80 
Also makes nodes join the cluster when running the cluster init script, and increase alpha constant.
> Fix parallelization

- internal/node/node.go
> Return k closest contacts when value not found

- internal/commands/put/put.go
> Return hash from put command

- internal/node/node.go
- internal/rpccommands/findvalue/findvalue.go
Successful get now returns both the data and the node id
Closes #94
> Add return data and node id

- internal/node/node.go
Extracts some common functionality between node lookup and data lookup.
> Refactor lookup probing

- internal/node/node.go
- internal/shortlist/shortlist.go
Closes #89 
Sends a store message to the closest node that did not return the value.
> Implement find value succesful behavior

- internal/node/node.go
Closes #98 
This also extracts common functionality for handling rpc responses into separate functions.
Noticed some incorrect behavior as well with the lookup data algorithm that i fixed.
> Send FIND_* rpcs to unprobed nodes when closest node is unchanged

- internal/node/node.go
- internal/rpc/parser/parser.go
- internal/rpccommands/findvalueresp/findvalueresp.go
> Return id of node storing value when value is found

- internal/contact/contact.go
- internal/contact/contact_test.go
- internal/kademliaid/kademliaid_test.go
Some tests were wrong and added more tests to contact
> Add more tests

- internal/contact/contact.go
- internal/node/node.go
Added check that prevents deserializeContacts() from passing "" empty strings to deserialize()
Closes #79
> Fix deserialize

- cmd/kademlia/kademlia.go
- docker-compose-dev.yml
- docker-compose-prod.yml
- internal/address/address.go
- internal/address/address_test.go
- internal/commands/addcontact/addcontact_test.go
- internal/contact/contact_test.go
- internal/udpsender/udpsender.go
Set which port to use for sending udp packets in env
Closes #114
> Add sender port to environment and set sender address

- internal/address/address.go
- internal/address/address_test.go
- internal/bucket/bucket.go
- internal/bucket/bucket_test.go
- internal/commands/addcontact/addcontact_test.go
- internal/commands/getcontacts/getcontacts_test.go
- internal/commands/initnode/initnode_test.go
- internal/commands/storage/storage.go
- internal/commands/storage/storage_test.go
- internal/contact/contact.go
- internal/contact/contact_test.go
- internal/datastore/datastore_test.go
- internal/kademliaid/kademliaid_test.go
- internal/node/node_test.go
- internal/routingtable/routingtable.go
- internal/routingtable/routingtable_test.go
- internal/rpc/parser/parser_test.go
- internal/rpccommands/findvalue/findvalue_test.go
- internal/rpccommands/findvalueresp/findvalueresp_test.go
- internal/shortlist/shortlist_test.go
Added some new tests which were missing and also rewrote some existing
tests to better test the functionality of the function under test.
None of the tests added required mocks so more tests will have to be
added in the future. Currently the total coverage is 60.4% after these
changes.
> Update and add more tests

- internal/udplistener/udplistener.go
When a message is read from UDP a goroutine is created
Closes #121
> Add go routine to udplistener

- docker-compose-dev.yml
- docker-compose-prod.yml
- internal/node/node.go
- internal/node/node_test.go
- internal/rpccommands/findnoderesp/findnoderesp_test.go
- internal/rpccommands/findvalueresp/findvalueresp_test.go
- internal/rpcpool/rpcpool.go
- internal/rpcpool/rpcpool_test.go
- internal/shortlist/shortlist.go
- internal/shortlist/shortlist_test.go
If timer expires, returns empty string and contact is dropped from shortlist. Otherwise return the data that is written to the channel
Closes #125
> Add timer to FIND_*_RESPONSE
