- cmd/kademlia/kademlia.go
- internal/node/node.go
Moved the kademlia node struct and methods from the main file and created
a global variable containing the node. This Node variable is initiliazed
when the node is created in the main function (currently only holds the
node id).
> Seperate Kademlia node from main

- cmd/kademliactl/kademliactl.go
- internal/command/parser/parser.go
- internal/commands/storage/storage.go
- internal/datastore/datastore.go
- internal/datastore/datastore_test.go
- internal/kademliaid/kademliaid.go
Closes #27, closes #28 
Adds a datastore, which is implemented as a map where the keys in the
key-value pairs are hashed created from the values.
Adds a command called store, which queries the node to print all stored
entries.
> Implement data storage

- internal/command/parser/parser.go
- internal/command/parser/parser_test.go
- internal/commands/get/get.go
- internal/commands/get/get_test.go
- internal/datastore/datastore.go
- internal/datastore/datastore_test.go
- internal/kademliaid/kademliaid.go
Closes #34, closes #35, closes #37 
At the moment it only looks for the value at the initiating node.
Also fixes an issue with incorrect hex value in the data storage.
> Implement local functionality and parsing of get cli command

- cmd/kademlia/kademlia.go
- internal/command/parser/parser.go
- internal/command/parser/parser_test.go
- internal/commands/addcontact/addcontact.go
- internal/commands/addcontact/addcontact_test.go
- internal/commands/getid/getid.go
- internal/commands/getid/getid_test.go
- internal/commands/initnode/initnode.go
- internal/commands/initnode/initnode_test.go
- internal/node/node.go
- internal/node/node_test.go
- scripts/init-cluster.sh
init-cluster.sh initilizes all the containers in the swarm by
initilizing each containers kademlia node. This is done by inspecting
each container and getting their IPs and then executing the node init
method to setup the node.
Finally, every node except one gets a known kademlia node added to their
routing table as a contact. This allows for the nodes to join the
network once we have implemented the FIND_NODE RPC later.
To implement this three new commands were added:
- getid: The getid command returns the node ID of the node running inside the container
- addcontact: Added a new command which adds a new contact to the nodes routing table given the nodeID and address of the other node.
- init: init takes the nodes local address as an argument since this is
required for the node to create …
> Implement shell script that initilizes the cluster

- internal/address/address.go
- internal/address/address_test.go
- internal/commands/addcontact/addcontact.go
- internal/commands/addcontact/addcontact_test.go
- internal/commands/initnode/initnode.go
- internal/commands/message/message.go
- internal/commands/ping/ping.go
- internal/commands/put/put.go
- internal/contact/contact.go
- internal/network/network.go
- internal/node/node.go
- internal/rpc/parser/parser.go
- internal/rpc/parser/parser_test.go
- internal/rpc/rpc.go
- internal/rpc/rpc_test.go
- internal/rpccommands/ping/ping.go
- internal/rpccommands/ping/ping_test.go
- internal/udplistener/udplistener.go
- internal/udpsender/udpsender.go
Address holds a host string and port string, it includes the net lib to split host and port from given address and also join them. I allows for the use of a env variable for port instead of hardcoding it in different classes
Closes #61
> Add Address to seperate host and port

- internal/routingtable/routingtable.go
Added if statment that prevents a node from adding itself to the routingtable if it e.g. pings itself
Closes #65
> Add prevent node from adding itself

- internal/commands/addcontact/addcontact_test.go
- internal/commands/getid/getid.go
- internal/commands/getid/getid_test.go
- internal/commands/initnode/initnode.go
- internal/globals/globals.go
- internal/network/network.go
- internal/node/node.go
- internal/node/node_test.go
- internal/rpc/rpc.go
- internal/rpcpool/rpcpool.go
Moves the node's ID to global scope (this will be reverted in a new pull request soon).
> Implement rpc pool

- internal/address/address.go
- internal/commands/addcontact/addcontact.go
- internal/commands/message/message.go
- internal/commands/ping/ping.go
- internal/node/node.go
- internal/rpc/parser/parser_test.go
- internal/rpc/rpc_test.go
- internal/rpccommands/ping/ping_test.go
- internal/udplistener/udplistener.go
Address is now returning a pointer to the struct, update to address splitting has been done to be more redundant
Closes #67
> 67 address pointer

- docker-compose-dev.yml
- internal/bucket/bucket.go
- internal/command/parser/parser.go
- internal/command/parser/parser_test.go
- internal/commands/join/join.go
- internal/commands/put/put.go
- internal/contact/contact.go
- internal/network/network.go
- internal/node/node.go
- internal/routingtable/routingtable.go
- internal/routingtable/routingtable_test.go
- internal/rpc/parser/parser.go
- internal/rpc/parser/parser_test.go
- internal/rpccommands/findnode/findnode.go
- internal/rpccommands/findnode/findnode_test.go
- internal/rpccommands/findnoderesp/findnoderesp.go
- internal/rpccommands/findnoderesp/findnoderesp_test.go
- internal/shortlist/shortlist.go
- internal/shortlist/shortlist_test.go
The lookup algorithm was implemented by following the description in the
kademlia specification. Note that the current version is still missing
some key features of the lookup algorithm since we are using alpha=1
which makes it non-parallel. This will be fixed once we have merged
Martins FIND_VALUE branch as well since we need to fix some underlying
issues to get the algortihm working with alpha>1. The logic behind what
happens if no improvement of the closest node has been made after one
iteration also has to be implemented later.
Added CLI commands:
- Join: For joining the network, only executes a node lookup on itself
to fill the nodes routing table with entries.
Added RPCs:
- findnode: Used by the node lookup algorithm to search on the specified
key (id) this is the FIND_NODE RPC.
- …
> Implement network joining and FIND_NODE RPC

- internal/command/command.go
- internal/command/parser/parser.go
- internal/commands/addcontact/addcontact.go
- internal/commands/addcontact/addcontact_test.go
- internal/commands/exit/exit.go
- internal/commands/exit/exit_test.go
- internal/commands/get/get.go
- internal/commands/get/get_test.go
- internal/commands/getcontacts/getcontacts.go
- internal/commands/getcontacts/getcontacts_test.go
- internal/commands/getid/getid.go
- internal/commands/getid/getid_test.go
- internal/commands/initnode/initnode.go
- internal/commands/initnode/initnode_test.go
- internal/commands/join/join.go
- internal/commands/join/join_test.go
- internal/commands/message/message.go
- internal/commands/message/message_test.go
- internal/commands/ping/ping.go
- internal/commands/ping/ping_test.go
- internal/commands/put/put.go
- internal/commands/put/put_test.go
- internal/commands/storage/storage.go
PrintUsage() in every cli command returns a string which is logged in the parser if usage is wrong
Closes #41 
P.S. added some tests :1st_place_medal:
> Add PrintUsage() return string and tests

- internal/commands/get/get.go
- internal/node/node.go
Uses k where alpha previously was incorrectly used.
Also makes the get command tell the user if the value was found locally.
> Correct constant and local value

- cmd/kademliactl/kademliactl.go
- internal/commands/getcontacts/getcontacts_test.go
- internal/kademliaid/kademliaid.go
- internal/kademliaid/kademliaid_test.go
- internal/node/node.go
- internal/routingtable/routingtable.go
- internal/routingtable/routingtable_test.go
The node now refreshes every bucket further away than the bucket its
closest neighbour resides in. This step is done after the initial node
lookup has been completed. The closest neighbour node is the first
contact in the list of contacts returned from the node lookup.
A bucket refresh is done by generating a new random ID within the
range of the bucket (for bucket i this is 2^i <= Distance(node, contact) < 2^(i+1))
and then performing a node lookup on that ID. This is repeated for all
buckets. This function can also be reused when implementing the bucket
refresh which is supposed to happen after no lookups have been made after
x time.
Implemented funcationality for generating a new NodeID which will be in
the range of a nodes bucket *i*. The implementation might be
hard to understand but …
> Implement the bucket refresh procedure of network joining

- cmd/kademlia/kademlia.go
- internal/logger/logger.go
Kademliactl should no longer log that a log level has been set every time a command is run.
> Don't log if log level is set in kademliactl

- internal/bucket/bucket.go
- internal/bucket/bucket_test.go
- internal/node/node.go
- internal/nodedata/nodedata.go
- internal/refreshtimer/refreshtimer.go
- internal/refreshtimer/refreshtimer_test.go
- internal/routingtable/routingtable.go
The buckets in the nodes routing table will now periodically refresh if
no node lookup has been done in the ID range of the bucket within a
specfied time. Each time a lookup is done within the buckets range this
timer is restarted. If this is not the case the bucket will instead be
refreshed using the nodes RefreshBucket() method.
The node now has a property RefreshTimers which is a list of refresh
timers, one for each bucket (excluding the last bucket since this will
whp be empty). The refresh timers are started by giving them a callback
function which will be executed once the timer runs out. The refresh
timer then restarts once again.
I started working with what @bugmana  had on the branch but began having problems with cyclic dependencies so I moved it to a separate file and added the …
> Implement timed bucket refreshes

- internal/datastore/datastore.go
- internal/node/node.go
TTL Node data
- When data is stored on a node a timer of 1 hour is started 
- When timer expires the data is deleted from the node store
- If the data is request on a node and retrieved from that node the timer is restarted, the data will still be dropped on the k-nodes if not explicitly requested on one of the k-nodes
- If data is put:ed (transmitted) the timer is overridden with a new timer of 1 hour
Closes #81
> 81 ttl data

- README.md
- cmd/kademlia/kademlia.go
- internal/http/listener/listener.go
- internal/http/listener/listener_test.go
Closes #86 
This implements to REST endpoints that can be used to interact with the nodes.
You can do a GET command by running the following:
```bash
curl <container-ip>:8080/objects/<hash>
```
You can do a POST (store) command by running the following:
```bash
curl -X POST <container-ip>:8080/objects -d "<content>"
```
> Implement REST api

- internal/commands/put/put.go
- internal/commands/storage/storage_test.go
- internal/datastore/datastore.go
- internal/datastore/datastore_test.go
- internal/http/listener/listener_test.go
- internal/node/node.go
- internal/node/node_test.go
- internal/routingtable/routingtable.go
- internal/rpc/parser/parser.go
- internal/rpccommands/refresh/refresh.go
- internal/rpccommands/refresh/refresh_test.go
- internal/rpccommands/store/store.go
- scripts/init-cluster.sh
Closes #82 
Please, make sure to test this carefully.
Now, when inserting into the datastore you have to pass a contact
pointer. If this pointer is non-nil then the node that is inserting is the node
where the insert was initiated, and if it is nil then it is not. This
means that this pointer will be non-nil when a node receives STORE
rpc-command and nil when a node receives the put cli-command.
Introduces a new rpc called REFRESH, which contains the hash of the file
to refresh and is used to tell another node to restart its refresh timer.
Also, each datastore entry takes a list of contacts that indicate at
which other contacts the value was stored when initially inserted. This
is used to remember which nodes to send REFRESH rpcs to.
> Implement TTL delay

- internal/command/parser/parser.go
- internal/commands/forget/forget.go
- internal/commands/forget/forget_test.go
- internal/datastore/datastore.go
Closes #83 
Each entry in the datastore now has a bool that indicates whether or not
the value has been marked as forgotten. If a value has been marked as
forgotten, then it will be deleted and no REFRESH rpcs will be sent to
the other node during the next refresh timer interval and the timer will
be stopped.
The kademlia spec doesn't really mention whether or not the value should be deleted at the initiator node (the one that receives the forget command) as far as i could see, but i think it makes the most sense, so implemented it that  way.
> Implement forget cli-command

- docker-compose-dev.yml
- docker-compose-prod.yml
- internal/command/parser/parser_test.go
- internal/commands/exit/exit.go
- internal/commands/exit/exit_test.go
- internal/commands/get/get_test.go
- internal/datastore/datastore.go
- internal/datastore/datastore_test.go
- internal/node/node.go
- internal/node/node_test.go
- internal/refreshtimer/refreshtimer.go
- internal/refreshtimer/refreshtimer_test.go
- internal/rpc/parser/parser_test.go
- internal/rpccommands/findnoderesp/findnoderesp_test.go
- internal/rpccommands/findvalueresp/findvalueresp_test.go
- internal/rpccommands/refresh/refresh_test.go
- internal/rpcpool/rpcpool_test.go
- internal/shortlist/shortlist_test.go
After this the main coverage we are missing is the LookupData and LookupNode methods in `node.go`. The problem with these methods (and the other ones we are still missing IRC) is that they use the other methods such as LookupDataHandleResponses, and these can't be mocked unless we rewrite using Interfaces so we can use these methods inside another function in the interface that we can mock.
PR on what we have so far at least (around ~70% coverage).
> Added multiple missing tests

- internal/node/node.go
- internal/node/node_test.go
- internal/refreshtimer/refreshtimer_test.go
Hopefully fixed an issue where one refreshtimer test would occasionally fail due to timing issues with sleep.
---
Added some tests to cover the branches of the lookup algo. This was done
by making the SetupLookUpAlgorithm function mockable. We can now mock it
and return variables which we can use during the test. This way we are
able to send data to the channels the lookup algo is waiting for to
simulate responses from other nodes. This is not the best approach but
at least we can test it now even though it requires a lot of waits and
is very tedious and error prone.
This commit also fixed an issue with the `LookupContact` algorithm that I noticed while running the tests. The problem was that when the closest contact did not improve we did not stop iterating if the final round of probes …
> Lookup tests

- docker-compose-prod.yml
Lowered the TTL and refresh time on prod to make it easier to demonstrate the functionality of the network in prod (which we will use during the sprint review)
> Update prod env vars
